FROM ubuntu:24.04

RUN apt update && apt install -y \
    libfontconfig1 \
    libx11-6 \
    libxcursor1 \
    libxinerama1 \
    libglu1-mesa \
    libasound2t64 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/godot

# COPY godot.x86_64 /opt/godot/godot.x86_64
COPY templates /opt/godot/templates

# RUN chmod +x /opt/godot/godot.x86_64

# ENV GODOT_TEMPLATES_DIR=/opt/godot/templates

# ENTRYPOINT ["/opt/godot/godot.x86_64"]