name: Build Godot Docker Image
on:
  workflow_dispatch:
  push:

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Clone Godot
        run: git clone https://github.com/godotengine/godot.git --depth 1
      
      - name: Upload sources
        uses: actions/upload-artifact@v4
        with:
          name: godot-source
          path: godot
  
  build_linux:
    runs-on: ubuntu-latest
    needs: prepare

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
        
      - name: Download Godot
        uses: actions/download-artifact@v4
        with:
          name: godot-source
          path: .
      
      - name: Cache SCons
        uses: actions/cache@v4
        with:
          path: ~/.scons_cache
          key: ${{ runner.os }}-scons-${{ hashFiles('godot/**') }}

      - name: Build build-containers images
        run: |
          chmod +x build-containers/build.sh

          cd build-containers

          sed -i '/podman_build windows/s/^/#/' build.sh
          sed -i '/podman_build web/s/^/#/' build.sh
          sed -i '/podman_build android/s/^/#/' build.sh
          sed -i '/podman_build osx/s/^/#/' build.sh
          sed -i '/podman_build appleembedded/s/^/#/' build.sh

          ./build.sh master f43

      - name: Build Linux template
        run: |
          docker run --rm \
          -v ${{ github.workspace }}/godot:/godot \
          -v $HOME/.scons_cache:/root/.scons_cache \
          -w /godot \
          godot-linux:master-f43 \
          bash -c 'export PATH=$GODOT_SDK_LINUX_X86_64/bin:$PATH && scons cache_path=/root/.scons_cache platform=linuxbsd target=template_release production=yes'
      
      - name: Build Linux editor
        run: |
          docker run --rm \
          -v ${{ github.workspace }}/godot:/godot \
          -v $HOME/.scons_cache:/root/.scons_cache \
          -w /godot \
          godot-linux:master-f43 \
          bash -c 'export PATH=$GODOT_SDK_LINUX_X86_64/bin:$PATH && scons cache_path=/root/.scons_cache platform=linuxbsd target=editor production=yes'


      - name: Upload linux binaries
        uses: actions/upload-artifact@v4
        with:
          name: linux-binaries
          path: godot/bin/*